name: xmpp_communication
description: Dart package which manages the xmpp communication.
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  xmpp_stone: 
    path: ../xmpp_dart
  signal:
    path: ../signal