name: signal
description: Package to manage the signal stuff.
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  libsignal_protocol_dart:
    path: ./../libsignal_protocol_dart
  http: ^0.13.3

dev_dependencies:
